language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
install: true
script: "./gradlew clean build jacocoTestReport coveralls"
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./publish.sh; fi
env:
  global:
  - CI_NAME=travis-ci
  - secure: uGO8W3VW7nYdumA/yCVaflhfYJm3cqyz6T07cKTW4F7ffr4NoQF6cxNf8O3fsmavINUKtRGfA/usO4xQ093YmOEAhcueTsGfgG5ve8dDIB9KJUSzToInmZVgWU6JojXjXqDOEN7SsAPJ4gV7JJkRcg0qbyuIGUEeyrmeZo3ExweKXyWGzF022AilgUFScP/MxClPEZY7C3ZI5lldcOT/PKk1H6ail2b6s2D3rC6gzSU20patVFLa1MBIyoCqS/vLmgYMSQsBuvZcdl10OPEZ7xmuAKrYJCG1ngH8RsO9rgaYLQVmuQXgUq6I5ij2fDdw3E/1VV6X5qdn5W6gzhG9QeiMxRISuapoGcHoRVJRgvKK/ir3cSJo0hKIQiqf9RA6Mzmdx4Eaz0JvHT/Zy9vfHm0rJtmdqsgD975NIsYamo2HiNUUE+nmoInf0KN1w8S8gngaGFzF+PBtvHO+MztjKWDJXwyh/AmFc/S81Me/NwIwKoM7ntPGPpU0jN0Y5UO9xsntHQQ0nIshH7ximY5dSpEWpfZCLAUZLU8jkx72gjToG8ReTa6VZ43bujdjv/+YrhB4sxlq1Lq1RRysFBBq/NJrDIbp43m8k5RVACT/32XRm1lBbp91JgzDIlD18kdOQhO+luLj31PMQWLzHhDNByzasbAnDkwp9NYQ++otRJQ=
