# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/restdocs-raml
    environment:
      JVM_OPTS: -Xmx1024m
      TERM: dumb
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "build.gradle" }}-{{ checksum  "restdocs-raml/build.gradle" }}-{{ checksum  "restdocs-raml-gradle-plugin/build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: dependencies-{{ checksum "build.gradle" }}-{{ checksum  "restdocs-raml/build.gradle" }}-{{ checksum  "restdocs-raml-gradle-plugin/build.gradle" }}
      - run: ./gradlew clean build jacocoTestReport coveralls
      - store_test_results:
          path: restdocs-raml/build/reports/tests
      - store_test_results:
          path: restdocs-raml-gradle-plugin/build/reports/tests



